name: Release
on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build pre-built binary
        run: npm ci && npm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *-linux
            *-macos
            *-win.exe